//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Serene_AMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInvoiceReceipt
    {
        public int InvoiceReceiptId { get; set; }
        public string InvoiceReceiptNo { get; set; }
        public Nullable<int> GRReferenceNo { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<decimal> PaidAmount { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public string Createdby { get; set; }
        public Nullable<System.DateTime> Createdon { get; set; }
        public string Status { get; set; }
    }
}
