//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Serene_AMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblreturnlineitem
    {
        public int Id { get; set; }
        public Nullable<int> ReturnNo { get; set; }
        public Nullable<int> Grreferenceno { get; set; }
        public Nullable<int> VendorId { get; set; }
        public Nullable<int> ItemId { get; set; }
        public Nullable<int> DeliveredQuantity { get; set; }
        public Nullable<int> RejectedQuantity { get; set; }
        public Nullable<int> ApprovedQtybyQuality { get; set; }
        public Nullable<int> MissingQuantity { get; set; }
        public Nullable<int> AvailableQuantity { get; set; }
        public Nullable<int> ReturnQuantity { get; set; }
        public Nullable<int> PartialReturnQuantity { get; set; }
        public Nullable<int> RemainingQuantity { get; set; }
        public string Approved { get; set; }
    }
}
