//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Serene_AMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRequestdetail
    {
        public int RequestId { get; set; }
        public Nullable<int> CompanyCode { get; set; }
        public Nullable<int> CityCode { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> PositionId { get; set; }
        public string Position { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public string EmployeeName { get; set; }
        public string ReasonofRequest { get; set; }
        public Nullable<System.DateTime> LastWorkingDate { get; set; }
    
        public virtual tblEmployee tblEmployee { get; set; }
    }
}
