//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Serene_AMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTest
    {
        public int TestId { get; set; }
        public Nullable<System.DateTime> TestDate { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> CandidateId { get; set; }
    
        public virtual tblCandidate tblCandidate { get; set; }
    }
}
